name: Build CV
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile CV document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: main.pdf

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Hien Pham
          author_email: hienduyph@gmail.com
          message: 'Build CV'
          add: '*.pdf'
          new_branch: dist
